import type { AppConfig, AuditEvent, ClusterStatus, DiagnosticCheck, DiscoveryCandidate, HardwareInfo, InstallStatus, JobSubmission, NodeInfo, SetupRunStatus, TerminalLogEntry } from "./types";

export const api = {
  health:               ()           => window.electronAPI.invoke('health') as Promise<{ ok: boolean; version: string; ray_available: boolean; ray_version?: string }>,
  getConfig:            ()           => window.electronAPI.invoke('get_config') as Promise<AppConfig>,
  saveConfig:           (cfg: AppConfig) => window.electronAPI.invoke('save_config', cfg as unknown as Record<string, unknown>) as Promise<AppConfig>,
  status:               ()           => window.electronAPI.invoke('cluster_status') as Promise<ClusterStatus>,
  diagnostics:          ()           => window.electronAPI.invoke('diagnostics') as Promise<DiagnosticCheck[]>,
  hardware:             ()           => window.electronAPI.invoke('hardware') as Promise<HardwareInfo>,
  terminalLogs:         ()           => window.electronAPI.invoke('terminal_logs') as Promise<TerminalLogEntry[]>,
  discoverCoordinators: ()           => window.electronAPI.invoke('discovery_coordinators') as Promise<DiscoveryCandidate[]>,
  rayInstallStatus:     ()           => window.electronAPI.invoke('ray_install_status') as Promise<InstallStatus>,
  installRay:           ()           => window.electronAPI.invoke('install_ray') as Promise<InstallStatus>,
  setupStatus:          ()           => window.electronAPI.invoke('setup_status') as Promise<SetupRunStatus>,
  runSetup:             ()           => window.electronAPI.invoke('run_setup') as Promise<SetupRunStatus>,
  start:                ()           => window.electronAPI.invoke('cluster_start') as Promise<ClusterStatus>,
  stop:                 ()           => window.electronAPI.invoke('cluster_stop') as Promise<ClusterStatus>,
  panic:                ()           => window.electronAPI.invoke('cluster_panic') as Promise<ClusterStatus>,
  nodes:                ()           => window.electronAPI.invoke('nodes') as Promise<NodeInfo[]>,
  audit:                ()           => window.electronAPI.invoke('audit') as Promise<AuditEvent[]>,
  createSubmitter:      (name: string) => window.electronAPI.invoke('create_submitter', { name }) as Promise<{ id: string; name: string; token: string }>,
  revokeSubmitter:      (id: string)  => window.electronAPI.invoke('revoke_submitter', { id }) as Promise<AppConfig>,
  submitJob:            (job: JobSubmission) => window.electronAPI.invoke('submit_job', job as unknown as Record<string, unknown>) as Promise<{ job_id: string; status: string; message: string }>,
  killJob:              (id: string)  => window.electronAPI.invoke('kill_job', { id }) as Promise<{ job_id: string; status: string; message: string }>,
};
